/* Generated by Yosys 0.43 (git sha1 ead4718e5, clang++ 15.0.0 -fPIC -Os) */

module tst(clk, in, out);
  input clk;
  wire clk;
  input [7:0] in;
  wire [7:0] in;
  output [7:0] out;
  wire [7:0] out;
  DFFPOSX1 _0_ (
    .CLK(clk),
    .D(in[0]),
    .Q(out[0])
  );
  DFFPOSX1 _1_ (
    .CLK(clk),
    .D(in[1]),
    .Q(out[1])
  );
  DFFPOSX1 _2_ (
    .CLK(clk),
    .D(in[2]),
    .Q(out[2])
  );
  DFFPOSX1 _3_ (
    .CLK(clk),
    .D(in[3]),
    .Q(out[3])
  );
  DFFPOSX1 _4_ (
    .CLK(clk),
    .D(in[4]),
    .Q(out[4])
  );
  DFFPOSX1 _5_ (
    .CLK(clk),
    .D(in[5]),
    .Q(out[5])
  );
  DFFPOSX1 _6_ (
    .CLK(clk),
    .D(in[6]),
    .Q(out[6])
  );
  DFFPOSX1 _7_ (
    .CLK(clk),
    .D(in[7]),
    .Q(out[7])
  );
endmodule
