/* Generated by Yosys 0.43 (git sha1 ead4718e5, clang++ 15.0.0 -fPIC -Os) */

module buffer_ready_valid(clk, rst, in_data, in_valid, in_ready, out_data, out_valid, out_ready);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire [7:0] buffer;
  input clk;
  wire clk;
  wire full;
  input [7:0] in_data;
  wire [7:0] in_data;
  output in_ready;
  wire in_ready;
  input in_valid;
  wire in_valid;
  output [7:0] out_data;
  wire [7:0] out_data;
  input out_ready;
  wire out_ready;
  output out_valid;
  wire out_valid;
  input rst;
  wire rst;
  INVX1 _045_ (
    .A(full),
    .Y(in_ready)
  );
  INVX1 _046_ (
    .A(rst),
    .Y(_000_)
  );
  INVX1 _047_ (
    .A(buffer[0]),
    .Y(_018_)
  );
  INVX1 _048_ (
    .A(in_data[0]),
    .Y(_019_)
  );
  INVX1 _049_ (
    .A(buffer[1]),
    .Y(_020_)
  );
  INVX1 _050_ (
    .A(in_data[1]),
    .Y(_021_)
  );
  INVX1 _051_ (
    .A(buffer[2]),
    .Y(_022_)
  );
  INVX1 _052_ (
    .A(in_data[2]),
    .Y(_023_)
  );
  INVX1 _053_ (
    .A(buffer[3]),
    .Y(_024_)
  );
  INVX1 _054_ (
    .A(in_data[3]),
    .Y(_025_)
  );
  INVX1 _055_ (
    .A(buffer[4]),
    .Y(_026_)
  );
  INVX1 _056_ (
    .A(in_data[4]),
    .Y(_027_)
  );
  INVX1 _057_ (
    .A(buffer[5]),
    .Y(_028_)
  );
  INVX1 _058_ (
    .A(in_data[5]),
    .Y(_029_)
  );
  INVX1 _059_ (
    .A(buffer[6]),
    .Y(_030_)
  );
  INVX1 _060_ (
    .A(in_data[6]),
    .Y(_031_)
  );
  INVX1 _061_ (
    .A(buffer[7]),
    .Y(_032_)
  );
  INVX1 _062_ (
    .A(in_data[7]),
    .Y(_033_)
  );
  NAND2X1 _063_ (
    .A(in_ready),
    .B(in_valid),
    .Y(_034_)
  );
  OAI21X1 _064_ (
    .A(in_ready),
    .B(out_ready),
    .C(_034_),
    .Y(_017_)
  );
  NAND3X1 _065_ (
    .A(in_ready),
    .B(_000_),
    .C(in_valid),
    .Y(_035_)
  );
  MUX2X1 _066_ (
    .A(_018_),
    .B(_019_),
    .S(_035_),
    .Y(_001_)
  );
  MUX2X1 _067_ (
    .A(_020_),
    .B(_021_),
    .S(_035_),
    .Y(_002_)
  );
  MUX2X1 _068_ (
    .A(_022_),
    .B(_023_),
    .S(_035_),
    .Y(_003_)
  );
  MUX2X1 _069_ (
    .A(_024_),
    .B(_025_),
    .S(_035_),
    .Y(_004_)
  );
  MUX2X1 _070_ (
    .A(_026_),
    .B(_027_),
    .S(_035_),
    .Y(_005_)
  );
  MUX2X1 _071_ (
    .A(_028_),
    .B(_029_),
    .S(_035_),
    .Y(_006_)
  );
  MUX2X1 _072_ (
    .A(_030_),
    .B(_031_),
    .S(_035_),
    .Y(_007_)
  );
  MUX2X1 _073_ (
    .A(_032_),
    .B(_033_),
    .S(_035_),
    .Y(_008_)
  );
  NAND2X1 _074_ (
    .A(full),
    .B(_000_),
    .Y(_036_)
  );
  OAI21X1 _075_ (
    .A(in_ready),
    .B(rst),
    .C(out_data[0]),
    .Y(_037_)
  );
  OAI21X1 _076_ (
    .A(_018_),
    .B(_036_),
    .C(_037_),
    .Y(_009_)
  );
  OAI21X1 _077_ (
    .A(in_ready),
    .B(rst),
    .C(out_data[1]),
    .Y(_038_)
  );
  OAI21X1 _078_ (
    .A(_020_),
    .B(_036_),
    .C(_038_),
    .Y(_010_)
  );
  OAI21X1 _079_ (
    .A(in_ready),
    .B(rst),
    .C(out_data[2]),
    .Y(_039_)
  );
  OAI21X1 _080_ (
    .A(_022_),
    .B(_036_),
    .C(_039_),
    .Y(_011_)
  );
  OAI21X1 _081_ (
    .A(in_ready),
    .B(rst),
    .C(out_data[3]),
    .Y(_040_)
  );
  OAI21X1 _082_ (
    .A(_024_),
    .B(_036_),
    .C(_040_),
    .Y(_012_)
  );
  OAI21X1 _083_ (
    .A(in_ready),
    .B(rst),
    .C(out_data[4]),
    .Y(_041_)
  );
  OAI21X1 _084_ (
    .A(_026_),
    .B(_036_),
    .C(_041_),
    .Y(_013_)
  );
  OAI21X1 _085_ (
    .A(in_ready),
    .B(rst),
    .C(out_data[5]),
    .Y(_042_)
  );
  OAI21X1 _086_ (
    .A(_028_),
    .B(_036_),
    .C(_042_),
    .Y(_014_)
  );
  OAI21X1 _087_ (
    .A(in_ready),
    .B(rst),
    .C(out_data[6]),
    .Y(_043_)
  );
  OAI21X1 _088_ (
    .A(_030_),
    .B(_036_),
    .C(_043_),
    .Y(_015_)
  );
  OAI21X1 _089_ (
    .A(in_ready),
    .B(rst),
    .C(out_data[7]),
    .Y(_044_)
  );
  OAI21X1 _090_ (
    .A(_032_),
    .B(_036_),
    .C(_044_),
    .Y(_016_)
  );
  DFFPOSX1 _091_ (
    .CLK(clk),
    .D(_001_),
    .Q(buffer[0])
  );
  DFFPOSX1 _092_ (
    .CLK(clk),
    .D(_002_),
    .Q(buffer[1])
  );
  DFFPOSX1 _093_ (
    .CLK(clk),
    .D(_003_),
    .Q(buffer[2])
  );
  DFFPOSX1 _094_ (
    .CLK(clk),
    .D(_004_),
    .Q(buffer[3])
  );
  DFFPOSX1 _095_ (
    .CLK(clk),
    .D(_005_),
    .Q(buffer[4])
  );
  DFFPOSX1 _096_ (
    .CLK(clk),
    .D(_006_),
    .Q(buffer[5])
  );
  DFFPOSX1 _097_ (
    .CLK(clk),
    .D(_007_),
    .Q(buffer[6])
  );
  DFFPOSX1 _098_ (
    .CLK(clk),
    .D(_008_),
    .Q(buffer[7])
  );
  DFFPOSX1 _099_ (
    .CLK(clk),
    .D(_009_),
    .Q(out_data[0])
  );
  DFFPOSX1 _100_ (
    .CLK(clk),
    .D(_010_),
    .Q(out_data[1])
  );
  DFFPOSX1 _101_ (
    .CLK(clk),
    .D(_011_),
    .Q(out_data[2])
  );
  DFFPOSX1 _102_ (
    .CLK(clk),
    .D(_012_),
    .Q(out_data[3])
  );
  DFFPOSX1 _103_ (
    .CLK(clk),
    .D(_013_),
    .Q(out_data[4])
  );
  DFFPOSX1 _104_ (
    .CLK(clk),
    .D(_014_),
    .Q(out_data[5])
  );
  DFFPOSX1 _105_ (
    .CLK(clk),
    .D(_015_),
    .Q(out_data[6])
  );
  DFFPOSX1 _106_ (
    .CLK(clk),
    .D(_016_),
    .Q(out_data[7])
  );
  DFFSR _107_ (
    .CLK(clk),
    .D(_017_),
    .Q(full),
    .R(_000_),
    .S(1'b1)
  );
  assign out_valid = full;
endmodule

module data_sink(clk, rst, in_data, in_valid, in_ready);
  wire _0_;
  input clk;
  wire clk;
  input [7:0] in_data;
  wire [7:0] in_data;
  output in_ready;
  wire in_ready;
  input in_valid;
  wire in_valid;
  input rst;
  wire rst;
  INVX1 _1_ (
    .A(rst),
    .Y(_0_)
  );
  DFFSR _2_ (
    .CLK(clk),
    .D(1'b1),
    .Q(in_ready),
    .R(_0_),
    .S(1'b1)
  );
endmodule

module data_source(clk, rst, out_data, out_valid, out_ready);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  input clk;
  wire clk;
  wire [31:0] i;
  output [7:0] out_data;
  wire [7:0] out_data;
  input out_ready;
  wire out_ready;
  output out_valid;
  wire out_valid;
  input rst;
  wire rst;
  INVX1 _153_ (
    .A(i[31]),
    .Y(_072_)
  );
  INVX1 _154_ (
    .A(i[28]),
    .Y(_073_)
  );
  INVX1 _155_ (
    .A(i[27]),
    .Y(_074_)
  );
  INVX1 _156_ (
    .A(i[24]),
    .Y(_075_)
  );
  INVX1 _157_ (
    .A(i[23]),
    .Y(_076_)
  );
  INVX1 _158_ (
    .A(i[22]),
    .Y(_077_)
  );
  INVX1 _159_ (
    .A(i[20]),
    .Y(_078_)
  );
  INVX1 _160_ (
    .A(i[19]),
    .Y(_079_)
  );
  INVX1 _161_ (
    .A(i[16]),
    .Y(_080_)
  );
  INVX1 _162_ (
    .A(i[15]),
    .Y(_081_)
  );
  INVX1 _163_ (
    .A(i[12]),
    .Y(_082_)
  );
  INVX1 _164_ (
    .A(i[11]),
    .Y(_083_)
  );
  INVX1 _165_ (
    .A(i[8]),
    .Y(_084_)
  );
  INVX1 _166_ (
    .A(i[7]),
    .Y(_085_)
  );
  INVX1 _167_ (
    .A(i[4]),
    .Y(_086_)
  );
  INVX1 _168_ (
    .A(i[3]),
    .Y(_087_)
  );
  INVX1 _169_ (
    .A(i[2]),
    .Y(_088_)
  );
  INVX1 _170_ (
    .A(rst),
    .Y(_001_)
  );
  NAND2X1 _171_ (
    .A(i[1]),
    .B(i[0]),
    .Y(_089_)
  );
  NOR2X1 _172_ (
    .A(i[13]),
    .B(i[10]),
    .Y(_090_)
  );
  NAND3X1 _173_ (
    .A(_082_),
    .B(_083_),
    .C(_090_),
    .Y(_091_)
  );
  NOR2X1 _174_ (
    .A(i[17]),
    .B(i[14]),
    .Y(_092_)
  );
  NAND3X1 _175_ (
    .A(_080_),
    .B(_081_),
    .C(_092_),
    .Y(_093_)
  );
  NOR3X1 _176_ (
    .A(i[5]),
    .B(i[4]),
    .C(i[3]),
    .Y(_094_)
  );
  NOR2X1 _177_ (
    .A(i[9]),
    .B(i[8]),
    .Y(_095_)
  );
  NOR2X1 _178_ (
    .A(i[7]),
    .B(i[6]),
    .Y(_096_)
  );
  NAND3X1 _179_ (
    .A(_094_),
    .B(_095_),
    .C(_096_),
    .Y(_097_)
  );
  NOR3X1 _180_ (
    .A(_091_),
    .B(_093_),
    .C(_097_),
    .Y(_098_)
  );
  NOR2X1 _181_ (
    .A(i[31]),
    .B(i[30]),
    .Y(_099_)
  );
  NOR2X1 _182_ (
    .A(i[29]),
    .B(i[28]),
    .Y(_100_)
  );
  NOR2X1 _183_ (
    .A(i[27]),
    .B(i[26]),
    .Y(_101_)
  );
  NAND3X1 _184_ (
    .A(_099_),
    .B(_100_),
    .C(_101_),
    .Y(_102_)
  );
  NOR2X1 _185_ (
    .A(i[25]),
    .B(i[24]),
    .Y(_103_)
  );
  NAND3X1 _186_ (
    .A(_076_),
    .B(_077_),
    .C(_103_),
    .Y(_104_)
  );
  NOR2X1 _187_ (
    .A(i[21]),
    .B(i[18]),
    .Y(_105_)
  );
  NAND3X1 _188_ (
    .A(_078_),
    .B(_079_),
    .C(_105_),
    .Y(_106_)
  );
  NOR3X1 _189_ (
    .A(_102_),
    .B(_104_),
    .C(_106_),
    .Y(_107_)
  );
  NAND3X1 _190_ (
    .A(_088_),
    .B(_098_),
    .C(_107_),
    .Y(_108_)
  );
  NAND2X1 _191_ (
    .A(_072_),
    .B(_108_),
    .Y(_000_)
  );
  AOI21X1 _192_ (
    .A(_072_),
    .B(_108_),
    .C(_089_),
    .Y(_109_)
  );
  NAND2X1 _193_ (
    .A(out_ready),
    .B(_000_),
    .Y(_110_)
  );
  NAND2X1 _194_ (
    .A(out_ready),
    .B(_109_),
    .Y(_111_)
  );
  NAND3X1 _195_ (
    .A(i[2]),
    .B(out_ready),
    .C(_109_),
    .Y(_112_)
  );
  NOR2X1 _196_ (
    .A(_087_),
    .B(_112_),
    .Y(_113_)
  );
  NOR3X1 _197_ (
    .A(_086_),
    .B(_087_),
    .C(_112_),
    .Y(_114_)
  );
  NAND2X1 _198_ (
    .A(i[5]),
    .B(_114_),
    .Y(_115_)
  );
  NAND3X1 _199_ (
    .A(i[6]),
    .B(i[5]),
    .C(_114_),
    .Y(_116_)
  );
  NOR2X1 _200_ (
    .A(_085_),
    .B(_116_),
    .Y(_117_)
  );
  NOR3X1 _201_ (
    .A(_084_),
    .B(_085_),
    .C(_116_),
    .Y(_118_)
  );
  NAND2X1 _202_ (
    .A(i[9]),
    .B(_118_),
    .Y(_119_)
  );
  NAND3X1 _203_ (
    .A(i[10]),
    .B(i[9]),
    .C(_118_),
    .Y(_120_)
  );
  OR2X1 _204_ (
    .A(_083_),
    .B(_120_),
    .Y(_121_)
  );
  NOR3X1 _205_ (
    .A(_082_),
    .B(_083_),
    .C(_120_),
    .Y(_122_)
  );
  NAND2X1 _206_ (
    .A(i[13]),
    .B(_122_),
    .Y(_123_)
  );
  NAND3X1 _207_ (
    .A(i[14]),
    .B(i[13]),
    .C(_122_),
    .Y(_124_)
  );
  NOR2X1 _208_ (
    .A(_081_),
    .B(_124_),
    .Y(_125_)
  );
  NOR3X1 _209_ (
    .A(_080_),
    .B(_081_),
    .C(_124_),
    .Y(_126_)
  );
  NAND2X1 _210_ (
    .A(i[17]),
    .B(_126_),
    .Y(_127_)
  );
  NAND3X1 _211_ (
    .A(i[18]),
    .B(i[17]),
    .C(_126_),
    .Y(_128_)
  );
  NOR2X1 _212_ (
    .A(_079_),
    .B(_128_),
    .Y(_129_)
  );
  NOR3X1 _213_ (
    .A(_078_),
    .B(_079_),
    .C(_128_),
    .Y(_130_)
  );
  AND2X1 _214_ (
    .A(i[21]),
    .B(_130_),
    .Y(_131_)
  );
  NAND3X1 _215_ (
    .A(i[22]),
    .B(i[21]),
    .C(_130_),
    .Y(_132_)
  );
  NOR2X1 _216_ (
    .A(_076_),
    .B(_132_),
    .Y(_133_)
  );
  NOR3X1 _217_ (
    .A(_075_),
    .B(_076_),
    .C(_132_),
    .Y(_134_)
  );
  AND2X1 _218_ (
    .A(i[25]),
    .B(_134_),
    .Y(_135_)
  );
  NAND3X1 _219_ (
    .A(i[26]),
    .B(i[25]),
    .C(_134_),
    .Y(_136_)
  );
  NOR2X1 _220_ (
    .A(_074_),
    .B(_136_),
    .Y(_137_)
  );
  NOR3X1 _221_ (
    .A(_073_),
    .B(_074_),
    .C(_136_),
    .Y(_138_)
  );
  AND2X1 _222_ (
    .A(i[29]),
    .B(_138_),
    .Y(_139_)
  );
  AOI21X1 _223_ (
    .A(i[30]),
    .B(_139_),
    .C(_072_),
    .Y(_071_)
  );
  XOR2X1 _224_ (
    .A(i[30]),
    .B(_139_),
    .Y(_070_)
  );
  XOR2X1 _225_ (
    .A(i[29]),
    .B(_138_),
    .Y(_069_)
  );
  NOR2X1 _226_ (
    .A(i[28]),
    .B(_137_),
    .Y(_140_)
  );
  NOR2X1 _227_ (
    .A(_138_),
    .B(_140_),
    .Y(_068_)
  );
  XNOR2X1 _228_ (
    .A(i[27]),
    .B(_136_),
    .Y(_067_)
  );
  XOR2X1 _229_ (
    .A(i[26]),
    .B(_135_),
    .Y(_066_)
  );
  NOR2X1 _230_ (
    .A(i[25]),
    .B(_134_),
    .Y(_141_)
  );
  NOR2X1 _231_ (
    .A(_135_),
    .B(_141_),
    .Y(_065_)
  );
  NOR2X1 _232_ (
    .A(i[24]),
    .B(_133_),
    .Y(_142_)
  );
  NOR2X1 _233_ (
    .A(_134_),
    .B(_142_),
    .Y(_064_)
  );
  XNOR2X1 _234_ (
    .A(i[23]),
    .B(_132_),
    .Y(_063_)
  );
  XNOR2X1 _235_ (
    .A(_077_),
    .B(_131_),
    .Y(_062_)
  );
  NOR2X1 _236_ (
    .A(i[21]),
    .B(_130_),
    .Y(_143_)
  );
  NOR2X1 _237_ (
    .A(_131_),
    .B(_143_),
    .Y(_061_)
  );
  NOR2X1 _238_ (
    .A(i[20]),
    .B(_129_),
    .Y(_144_)
  );
  NOR2X1 _239_ (
    .A(_130_),
    .B(_144_),
    .Y(_060_)
  );
  XNOR2X1 _240_ (
    .A(i[19]),
    .B(_128_),
    .Y(_059_)
  );
  XNOR2X1 _241_ (
    .A(i[18]),
    .B(_127_),
    .Y(_058_)
  );
  XOR2X1 _242_ (
    .A(i[17]),
    .B(_126_),
    .Y(_057_)
  );
  NOR2X1 _243_ (
    .A(i[16]),
    .B(_125_),
    .Y(_145_)
  );
  NOR2X1 _244_ (
    .A(_126_),
    .B(_145_),
    .Y(_056_)
  );
  XNOR2X1 _245_ (
    .A(i[15]),
    .B(_124_),
    .Y(_055_)
  );
  XNOR2X1 _246_ (
    .A(i[14]),
    .B(_123_),
    .Y(_054_)
  );
  XOR2X1 _247_ (
    .A(i[13]),
    .B(_122_),
    .Y(_053_)
  );
  XNOR2X1 _248_ (
    .A(i[12]),
    .B(_121_),
    .Y(_052_)
  );
  XNOR2X1 _249_ (
    .A(i[11]),
    .B(_120_),
    .Y(_051_)
  );
  XNOR2X1 _250_ (
    .A(i[10]),
    .B(_119_),
    .Y(_050_)
  );
  XOR2X1 _251_ (
    .A(i[9]),
    .B(_118_),
    .Y(_049_)
  );
  NOR2X1 _252_ (
    .A(i[8]),
    .B(_117_),
    .Y(_146_)
  );
  NOR2X1 _253_ (
    .A(_118_),
    .B(_146_),
    .Y(_048_)
  );
  XNOR2X1 _254_ (
    .A(i[7]),
    .B(_116_),
    .Y(_047_)
  );
  XNOR2X1 _255_ (
    .A(i[6]),
    .B(_115_),
    .Y(_046_)
  );
  XOR2X1 _256_ (
    .A(i[5]),
    .B(_114_),
    .Y(_045_)
  );
  NOR2X1 _257_ (
    .A(i[4]),
    .B(_113_),
    .Y(_147_)
  );
  NOR2X1 _258_ (
    .A(_114_),
    .B(_147_),
    .Y(_044_)
  );
  XNOR2X1 _259_ (
    .A(i[3]),
    .B(_112_),
    .Y(_043_)
  );
  XNOR2X1 _260_ (
    .A(i[2]),
    .B(_111_),
    .Y(_042_)
  );
  XNOR2X1 _261_ (
    .A(i[1]),
    .B(i[0]),
    .Y(_148_)
  );
  NAND2X1 _262_ (
    .A(i[1]),
    .B(_110_),
    .Y(_149_)
  );
  OAI21X1 _263_ (
    .A(_110_),
    .B(_148_),
    .C(_149_),
    .Y(_041_)
  );
  XNOR2X1 _264_ (
    .A(i[0]),
    .B(_110_),
    .Y(_040_)
  );
  NOR2X1 _265_ (
    .A(out_data[5]),
    .B(_000_),
    .Y(_150_)
  );
  AOI21X1 _266_ (
    .A(_000_),
    .B(_148_),
    .C(_150_),
    .Y(_039_)
  );
  NOR2X1 _267_ (
    .A(out_data[4]),
    .B(_000_),
    .Y(_151_)
  );
  AOI21X1 _268_ (
    .A(i[0]),
    .B(_000_),
    .C(_151_),
    .Y(_038_)
  );
  NOR2X1 _269_ (
    .A(out_data[2]),
    .B(_000_),
    .Y(_152_)
  );
  AOI21X1 _270_ (
    .A(_089_),
    .B(_000_),
    .C(_152_),
    .Y(_037_)
  );
  INVX1 _271_ (
    .A(rst),
    .Y(_002_)
  );
  INVX1 _272_ (
    .A(rst),
    .Y(_003_)
  );
  INVX1 _273_ (
    .A(rst),
    .Y(_004_)
  );
  INVX1 _274_ (
    .A(rst),
    .Y(_005_)
  );
  INVX1 _275_ (
    .A(rst),
    .Y(_006_)
  );
  INVX1 _276_ (
    .A(rst),
    .Y(_007_)
  );
  INVX1 _277_ (
    .A(rst),
    .Y(_008_)
  );
  INVX1 _278_ (
    .A(rst),
    .Y(_009_)
  );
  INVX1 _279_ (
    .A(rst),
    .Y(_010_)
  );
  INVX1 _280_ (
    .A(rst),
    .Y(_011_)
  );
  INVX1 _281_ (
    .A(rst),
    .Y(_012_)
  );
  INVX1 _282_ (
    .A(rst),
    .Y(_013_)
  );
  INVX1 _283_ (
    .A(rst),
    .Y(_014_)
  );
  INVX1 _284_ (
    .A(rst),
    .Y(_015_)
  );
  INVX1 _285_ (
    .A(rst),
    .Y(_016_)
  );
  INVX1 _286_ (
    .A(rst),
    .Y(_017_)
  );
  INVX1 _287_ (
    .A(rst),
    .Y(_018_)
  );
  INVX1 _288_ (
    .A(rst),
    .Y(_019_)
  );
  INVX1 _289_ (
    .A(rst),
    .Y(_020_)
  );
  INVX1 _290_ (
    .A(rst),
    .Y(_021_)
  );
  INVX1 _291_ (
    .A(rst),
    .Y(_022_)
  );
  INVX1 _292_ (
    .A(rst),
    .Y(_023_)
  );
  INVX1 _293_ (
    .A(rst),
    .Y(_024_)
  );
  INVX1 _294_ (
    .A(rst),
    .Y(_025_)
  );
  INVX1 _295_ (
    .A(rst),
    .Y(_026_)
  );
  INVX1 _296_ (
    .A(rst),
    .Y(_027_)
  );
  INVX1 _297_ (
    .A(rst),
    .Y(_028_)
  );
  INVX1 _298_ (
    .A(rst),
    .Y(_029_)
  );
  INVX1 _299_ (
    .A(rst),
    .Y(_030_)
  );
  INVX1 _300_ (
    .A(rst),
    .Y(_031_)
  );
  INVX1 _301_ (
    .A(rst),
    .Y(_032_)
  );
  INVX1 _302_ (
    .A(rst),
    .Y(_033_)
  );
  INVX1 _303_ (
    .A(rst),
    .Y(_034_)
  );
  INVX1 _304_ (
    .A(rst),
    .Y(_035_)
  );
  INVX1 _305_ (
    .A(rst),
    .Y(_036_)
  );
  DFFSR _306_ (
    .CLK(clk),
    .D(_037_),
    .Q(out_data[2]),
    .R(_001_),
    .S(1'b1)
  );
  DFFSR _307_ (
    .CLK(clk),
    .D(_038_),
    .Q(out_data[4]),
    .R(_002_),
    .S(1'b1)
  );
  DFFSR _308_ (
    .CLK(clk),
    .D(_039_),
    .Q(out_data[5]),
    .R(_003_),
    .S(1'b1)
  );
  DFFSR _309_ (
    .CLK(clk),
    .D(_000_),
    .Q(out_valid),
    .R(_004_),
    .S(1'b1)
  );
  DFFSR _310_ (
    .CLK(clk),
    .D(_040_),
    .Q(i[0]),
    .R(_005_),
    .S(1'b1)
  );
  DFFSR _311_ (
    .CLK(clk),
    .D(_041_),
    .Q(i[1]),
    .R(_006_),
    .S(1'b1)
  );
  DFFSR _312_ (
    .CLK(clk),
    .D(_042_),
    .Q(i[2]),
    .R(_007_),
    .S(1'b1)
  );
  DFFSR _313_ (
    .CLK(clk),
    .D(_043_),
    .Q(i[3]),
    .R(_008_),
    .S(1'b1)
  );
  DFFSR _314_ (
    .CLK(clk),
    .D(_044_),
    .Q(i[4]),
    .R(_009_),
    .S(1'b1)
  );
  DFFSR _315_ (
    .CLK(clk),
    .D(_045_),
    .Q(i[5]),
    .R(_010_),
    .S(1'b1)
  );
  DFFSR _316_ (
    .CLK(clk),
    .D(_046_),
    .Q(i[6]),
    .R(_011_),
    .S(1'b1)
  );
  DFFSR _317_ (
    .CLK(clk),
    .D(_047_),
    .Q(i[7]),
    .R(_012_),
    .S(1'b1)
  );
  DFFSR _318_ (
    .CLK(clk),
    .D(_048_),
    .Q(i[8]),
    .R(_013_),
    .S(1'b1)
  );
  DFFSR _319_ (
    .CLK(clk),
    .D(_049_),
    .Q(i[9]),
    .R(_014_),
    .S(1'b1)
  );
  DFFSR _320_ (
    .CLK(clk),
    .D(_050_),
    .Q(i[10]),
    .R(_015_),
    .S(1'b1)
  );
  DFFSR _321_ (
    .CLK(clk),
    .D(_051_),
    .Q(i[11]),
    .R(_016_),
    .S(1'b1)
  );
  DFFSR _322_ (
    .CLK(clk),
    .D(_052_),
    .Q(i[12]),
    .R(_017_),
    .S(1'b1)
  );
  DFFSR _323_ (
    .CLK(clk),
    .D(_053_),
    .Q(i[13]),
    .R(_018_),
    .S(1'b1)
  );
  DFFSR _324_ (
    .CLK(clk),
    .D(_054_),
    .Q(i[14]),
    .R(_019_),
    .S(1'b1)
  );
  DFFSR _325_ (
    .CLK(clk),
    .D(_055_),
    .Q(i[15]),
    .R(_020_),
    .S(1'b1)
  );
  DFFSR _326_ (
    .CLK(clk),
    .D(_056_),
    .Q(i[16]),
    .R(_021_),
    .S(1'b1)
  );
  DFFSR _327_ (
    .CLK(clk),
    .D(_057_),
    .Q(i[17]),
    .R(_022_),
    .S(1'b1)
  );
  DFFSR _328_ (
    .CLK(clk),
    .D(_058_),
    .Q(i[18]),
    .R(_023_),
    .S(1'b1)
  );
  DFFSR _329_ (
    .CLK(clk),
    .D(_059_),
    .Q(i[19]),
    .R(_024_),
    .S(1'b1)
  );
  DFFSR _330_ (
    .CLK(clk),
    .D(_060_),
    .Q(i[20]),
    .R(_025_),
    .S(1'b1)
  );
  DFFSR _331_ (
    .CLK(clk),
    .D(_061_),
    .Q(i[21]),
    .R(_026_),
    .S(1'b1)
  );
  DFFSR _332_ (
    .CLK(clk),
    .D(_062_),
    .Q(i[22]),
    .R(_027_),
    .S(1'b1)
  );
  DFFSR _333_ (
    .CLK(clk),
    .D(_063_),
    .Q(i[23]),
    .R(_028_),
    .S(1'b1)
  );
  DFFSR _334_ (
    .CLK(clk),
    .D(_064_),
    .Q(i[24]),
    .R(_029_),
    .S(1'b1)
  );
  DFFSR _335_ (
    .CLK(clk),
    .D(_065_),
    .Q(i[25]),
    .R(_030_),
    .S(1'b1)
  );
  DFFSR _336_ (
    .CLK(clk),
    .D(_066_),
    .Q(i[26]),
    .R(_031_),
    .S(1'b1)
  );
  DFFSR _337_ (
    .CLK(clk),
    .D(_067_),
    .Q(i[27]),
    .R(_032_),
    .S(1'b1)
  );
  DFFSR _338_ (
    .CLK(clk),
    .D(_068_),
    .Q(i[28]),
    .R(_033_),
    .S(1'b1)
  );
  DFFSR _339_ (
    .CLK(clk),
    .D(_069_),
    .Q(i[29]),
    .R(_034_),
    .S(1'b1)
  );
  DFFSR _340_ (
    .CLK(clk),
    .D(_070_),
    .Q(i[30]),
    .R(_035_),
    .S(1'b1)
  );
  DFFSR _341_ (
    .CLK(clk),
    .D(_071_),
    .Q(i[31]),
    .R(_036_),
    .S(1'b1)
  );
  assign out_data[1:0] = out_data[5:4];
  assign out_data[3] = 1'b0;
  assign out_data[7:6] = { 1'b0, out_data[2] };
endmodule

module tb_buffer_with_source_sink(rst, clk, src_valid, src_ready, buf_ready);
  wire [7:0] buf_out;
  output buf_ready;
  wire buf_ready;
  wire buf_valid;
  input clk;
  wire clk;
  input rst;
  wire rst;
  wire [7:0] src_data;
  output src_ready;
  wire src_ready;
  output src_valid;
  wire src_valid;
  buffer_ready_valid buffer (
    .clk(clk),
    .in_data(src_data),
    .in_ready(src_ready),
    .in_valid(src_valid),
    .out_data(buf_out),
    .out_ready(buf_ready),
    .out_valid(buf_valid),
    .rst(rst)
  );
  data_sink sink (
    .clk(clk),
    .in_data(buf_out),
    .in_ready(buf_ready),
    .in_valid(buf_valid),
    .rst(rst)
  );
  data_source source (
    .clk(clk),
    .out_data(src_data),
    .out_ready(src_ready),
    .out_valid(src_valid),
    .rst(rst)
  );
endmodule
