/* Generated by Yosys 0.43 (git sha1 ead4718e5, clang++ 15.0.0 -fPIC -Os) */

module buffer_ready_valid(clk, rst, in_data, in_valid, in_ready, out_data, out_valid, out_ready);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  input clk;
  wire clk;
  wire full;
  input [7:0] in_data;
  wire [7:0] in_data;
  output in_ready;
  wire in_ready;
  input in_valid;
  wire in_valid;
  output [7:0] out_data;
  wire [7:0] out_data;
  input out_ready;
  wire out_ready;
  output out_valid;
  wire out_valid;
  input rst;
  wire rst;
  C12T28SOI_LR_IVX4_P0 _45_ (
    .A(full),
    .Z(in_ready)
  );
  C12T28SOI_LR_IVX4_P0 _46_ (
    .A(_00_),
    .Z(out_data[7])
  );
  C12T28SOI_LR_IVX4_P0 _47_ (
    .A(_01_),
    .Z(out_data[6])
  );
  C12T28SOI_LR_IVX4_P0 _48_ (
    .A(_02_),
    .Z(out_data[5])
  );
  C12T28SOI_LR_IVX4_P0 _49_ (
    .A(_03_),
    .Z(out_data[4])
  );
  C12T28SOI_LR_IVX4_P0 _50_ (
    .A(_04_),
    .Z(out_data[3])
  );
  C12T28SOI_LR_IVX4_P0 _51_ (
    .A(_05_),
    .Z(out_data[2])
  );
  C12T28SOI_LR_IVX4_P0 _52_ (
    .A(_06_),
    .Z(out_data[1])
  );
  C12T28SOI_LR_IVX4_P0 _53_ (
    .A(_07_),
    .Z(out_data[0])
  );
  C12T28SOI_LR_IVX4_P0 _54_ (
    .A(rst),
    .Z(_16_)
  );
  C12T28SOI_LR_IVX4_P0 _55_ (
    .A(in_data[0]),
    .Z(_34_)
  );
  C12T28SOI_LR_IVX4_P0 _56_ (
    .A(in_data[1]),
    .Z(_35_)
  );
  C12T28SOI_LR_IVX4_P0 _57_ (
    .A(in_data[2]),
    .Z(_36_)
  );
  C12T28SOI_LR_IVX4_P0 _58_ (
    .A(in_data[3]),
    .Z(_37_)
  );
  C12T28SOI_LR_IVX4_P0 _59_ (
    .A(in_data[4]),
    .Z(_38_)
  );
  C12T28SOI_LR_IVX4_P0 _60_ (
    .A(in_data[5]),
    .Z(_39_)
  );
  C12T28SOI_LR_IVX4_P0 _61_ (
    .A(in_data[6]),
    .Z(_40_)
  );
  C12T28SOI_LR_IVX4_P0 _62_ (
    .A(in_data[7]),
    .Z(_41_)
  );
  C12T28SOI_LR_NAND2AX3_P0 _63_ (
    .A(full),
    .B(in_valid),
    .Z(_42_)
  );
  C12T28SOI_LR_OAI12X6_P0 _64_ (
    .A(in_ready),
    .B(out_ready),
    .C(_42_),
    .Z(_33_)
  );
  C12T28SOI_LR_NOR3AX6_P0 _65_ (
    .A(in_valid),
    .B(rst),
    .C(full),
    .Z(_43_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _66_ (
    .D0(_15_),
    .D1(_34_),
    .S0(_43_),
    .Z(_17_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _67_ (
    .D0(_14_),
    .D1(_35_),
    .S0(_43_),
    .Z(_18_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _68_ (
    .D0(_13_),
    .D1(_36_),
    .S0(_43_),
    .Z(_19_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _69_ (
    .D0(_12_),
    .D1(_37_),
    .S0(_43_),
    .Z(_20_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _70_ (
    .D0(_11_),
    .D1(_38_),
    .S0(_43_),
    .Z(_21_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _71_ (
    .D0(_10_),
    .D1(_39_),
    .S0(_43_),
    .Z(_22_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _72_ (
    .D0(_09_),
    .D1(_40_),
    .S0(_43_),
    .Z(_23_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _73_ (
    .D0(_08_),
    .D1(_41_),
    .S0(_43_),
    .Z(_24_)
  );
  C12T28SOI_LR_NOR2AX3_P0 _74_ (
    .A(full),
    .B(rst),
    .Z(_44_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _75_ (
    .D0(_07_),
    .D1(_15_),
    .S0(_44_),
    .Z(_25_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _76_ (
    .D0(_06_),
    .D1(_14_),
    .S0(_44_),
    .Z(_26_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _77_ (
    .D0(_05_),
    .D1(_13_),
    .S0(_44_),
    .Z(_27_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _78_ (
    .D0(_04_),
    .D1(_12_),
    .S0(_44_),
    .Z(_28_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _79_ (
    .D0(_03_),
    .D1(_11_),
    .S0(_44_),
    .Z(_29_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _80_ (
    .D0(_02_),
    .D1(_10_),
    .S0(_44_),
    .Z(_30_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _81_ (
    .D0(_01_),
    .D1(_09_),
    .S0(_44_),
    .Z(_31_)
  );
  C12T28SOI_LR_MUXI21X3_P0 _82_ (
    .D0(_00_),
    .D1(_08_),
    .S0(_44_),
    .Z(_32_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _83_ (
    .CP(clk),
    .D(_17_),
    .QN(_15_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _84_ (
    .CP(clk),
    .D(_18_),
    .QN(_14_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _85_ (
    .CP(clk),
    .D(_19_),
    .QN(_13_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _86_ (
    .CP(clk),
    .D(_20_),
    .QN(_12_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _87_ (
    .CP(clk),
    .D(_21_),
    .QN(_11_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _88_ (
    .CP(clk),
    .D(_22_),
    .QN(_10_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _89_ (
    .CP(clk),
    .D(_23_),
    .QN(_09_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _90_ (
    .CP(clk),
    .D(_24_),
    .QN(_08_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _91_ (
    .CP(clk),
    .D(_25_),
    .QN(_07_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _92_ (
    .CP(clk),
    .D(_26_),
    .QN(_06_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _93_ (
    .CP(clk),
    .D(_27_),
    .QN(_05_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _94_ (
    .CP(clk),
    .D(_28_),
    .QN(_04_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _95_ (
    .CP(clk),
    .D(_29_),
    .QN(_03_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _96_ (
    .CP(clk),
    .D(_30_),
    .QN(_02_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _97_ (
    .CP(clk),
    .D(_31_),
    .QN(_01_)
  );
  C12T28SOI_LR_DFPQNX8_P0 _98_ (
    .CP(clk),
    .D(_32_),
    .QN(_00_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _99_ (
    .CP(clk),
    .D(_33_),
    .Q(full),
    .RN(_16_)
  );
  assign out_valid = full;
endmodule

module data_sink(clk, rst, in_data, in_valid, in_ready);
  wire _0_;
  input clk;
  wire clk;
  input [7:0] in_data;
  wire [7:0] in_data;
  output in_ready;
  wire in_ready;
  input in_valid;
  wire in_valid;
  input rst;
  wire rst;
  C12T28SOI_LR_IVX4_P0 _1_ (
    .A(rst),
    .Z(_0_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _2_ (
    .CP(clk),
    .D(1'b1),
    .Q(in_ready),
    .RN(_0_)
  );
endmodule

module data_source(clk, rst, out_data, out_valid, out_ready);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  input clk;
  wire clk;
  wire [31:0] i;
  output [7:0] out_data;
  wire [7:0] out_data;
  input out_ready;
  wire out_ready;
  output out_valid;
  wire out_valid;
  input rst;
  wire rst;
  C12T28SOI_LR_IVX4_P0 _125_ (
    .A(i[31]),
    .Z(_072_)
  );
  C12T28SOI_LR_IVX4_P0 _126_ (
    .A(i[2]),
    .Z(_073_)
  );
  C12T28SOI_LR_IVX4_P0 _127_ (
    .A(out_ready),
    .Z(_074_)
  );
  C12T28SOI_LR_IVX4_P0 _128_ (
    .A(rst),
    .Z(_001_)
  );
  C12T28SOI_LR_NAND2X3_P0 _129_ (
    .A(i[1]),
    .B(i[0]),
    .Z(_075_)
  );
  C12T28SOI_LR_NOR3X4_P0 _130_ (
    .A(i[22]),
    .B(i[21]),
    .C(i[6]),
    .Z(_076_)
  );
  C12T28SOI_LR_NOR3X4_P0 _131_ (
    .A(i[12]),
    .B(i[8]),
    .C(i[3]),
    .Z(_077_)
  );
  C12T28SOI_LR_NOR3X4_P0 _132_ (
    .A(i[31]),
    .B(i[28]),
    .C(i[19]),
    .Z(_078_)
  );
  C12T28SOI_LR_NOR3X4_P0 _133_ (
    .A(i[23]),
    .B(i[18]),
    .C(i[17]),
    .Z(_079_)
  );
  C12T28SOI_LR_AND4X4_P0 _134_ (
    .A(_076_),
    .B(_077_),
    .C(_078_),
    .D(_079_),
    .Z(_080_)
  );
  C12T28SOI_LR_OR2X8_P0 _135_ (
    .A(i[29]),
    .B(i[27]),
    .Z(_081_)
  );
  C12T28SOI_LR_OR2X8_P0 _136_ (
    .A(i[30]),
    .B(i[24]),
    .Z(_082_)
  );
  C12T28SOI_LR_NOR3X4_P0 _137_ (
    .A(i[11]),
    .B(_081_),
    .C(_082_),
    .Z(_083_)
  );
  C12T28SOI_LR_NOR4ABX6_P0 _138_ (
    .A(_080_),
    .B(_083_),
    .C(i[10]),
    .D(i[9]),
    .Z(_084_)
  );
  C12T28SOI_LR_NOR3X4_P0 _139_ (
    .A(i[7]),
    .B(i[5]),
    .C(i[4]),
    .Z(_085_)
  );
  C12T28SOI_LR_NOR3X4_P0 _140_ (
    .A(i[26]),
    .B(i[25]),
    .C(i[14]),
    .Z(_086_)
  );
  C12T28SOI_LR_NAND4ABX6_P0 _141_ (
    .A(i[15]),
    .B(i[13]),
    .C(_085_),
    .D(_086_),
    .Z(_087_)
  );
  C12T28SOI_LR_NOR3X4_P0 _142_ (
    .A(i[20]),
    .B(i[16]),
    .C(_087_),
    .Z(_088_)
  );
  C12T28SOI_LR_AOI13X5_P0 _143_ (
    .A(_073_),
    .B(_084_),
    .C(_088_),
    .D(i[31]),
    .Z(_089_)
  );
  C12T28SOI_LR_IVX4_P0 _144_ (
    .A(_089_),
    .Z(_000_)
  );
  C12T28SOI_LR_NAND2X3_P0 _145_ (
    .A(out_ready),
    .B(_000_),
    .Z(_090_)
  );
  C12T28SOI_LR_NOR2X3_P0 _146_ (
    .A(_075_),
    .B(_090_),
    .Z(_091_)
  );
  C12T28SOI_LR_NOR4ABX6_P0 _147_ (
    .A(i[31]),
    .B(i[2]),
    .C(_074_),
    .D(_075_),
    .Z(_092_)
  );
  C12T28SOI_LR_NAND2X3_P0 _148_ (
    .A(i[3]),
    .B(_092_),
    .Z(_093_)
  );
  C12T28SOI_LR_AND4X4_P0 _149_ (
    .A(i[5]),
    .B(i[4]),
    .C(i[3]),
    .D(_092_),
    .Z(_094_)
  );
  C12T28SOI_LR_NAND2X3_P0 _150_ (
    .A(i[6]),
    .B(_094_),
    .Z(_095_)
  );
  C12T28SOI_LR_AND4X4_P0 _151_ (
    .A(i[8]),
    .B(i[7]),
    .C(i[6]),
    .D(_094_),
    .Z(_096_)
  );
  C12T28SOI_LR_NAND2X3_P0 _152_ (
    .A(i[9]),
    .B(_096_),
    .Z(_097_)
  );
  C12T28SOI_LR_AND4X4_P0 _153_ (
    .A(i[11]),
    .B(i[10]),
    .C(i[9]),
    .D(_096_),
    .Z(_098_)
  );
  C12T28SOI_LR_NAND2X3_P0 _154_ (
    .A(i[12]),
    .B(_098_),
    .Z(_099_)
  );
  C12T28SOI_LR_AND4X4_P0 _155_ (
    .A(i[14]),
    .B(i[13]),
    .C(i[12]),
    .D(_098_),
    .Z(_100_)
  );
  C12T28SOI_LR_NAND2X3_P0 _156_ (
    .A(i[15]),
    .B(_100_),
    .Z(_101_)
  );
  C12T28SOI_LR_AND4X4_P0 _157_ (
    .A(i[17]),
    .B(i[16]),
    .C(i[15]),
    .D(_100_),
    .Z(_102_)
  );
  C12T28SOI_LR_NAND2X3_P0 _158_ (
    .A(i[18]),
    .B(_102_),
    .Z(_103_)
  );
  C12T28SOI_LR_AND4X4_P0 _159_ (
    .A(i[20]),
    .B(i[19]),
    .C(i[18]),
    .D(_102_),
    .Z(_104_)
  );
  C12T28SOI_LR_NAND2X3_P0 _160_ (
    .A(i[21]),
    .B(_104_),
    .Z(_105_)
  );
  C12T28SOI_LR_AND4X4_P0 _161_ (
    .A(i[23]),
    .B(i[22]),
    .C(i[21]),
    .D(_104_),
    .Z(_106_)
  );
  C12T28SOI_LR_NAND2X3_P0 _162_ (
    .A(i[24]),
    .B(_106_),
    .Z(_107_)
  );
  C12T28SOI_LR_AND4X4_P0 _163_ (
    .A(i[26]),
    .B(i[25]),
    .C(i[24]),
    .D(_106_),
    .Z(_108_)
  );
  C12T28SOI_LR_AND3X8_P0 _164_ (
    .A(i[28]),
    .B(i[27]),
    .C(_108_),
    .Z(_109_)
  );
  C12T28SOI_LR_AND4X4_P0 _165_ (
    .A(i[29]),
    .B(i[28]),
    .C(i[27]),
    .D(_108_),
    .Z(_110_)
  );
  C12T28SOI_LR_AOI12X6_P0 _166_ (
    .A(i[30]),
    .B(_110_),
    .C(_072_),
    .Z(_071_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _167_ (
    .A(i[30]),
    .B(_110_),
    .Z(_070_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _168_ (
    .A(i[29]),
    .B(_109_),
    .Z(_069_)
  );
  C12T28SOI_LR_AOI12X6_P0 _169_ (
    .A(i[27]),
    .B(_108_),
    .C(i[28]),
    .Z(_111_)
  );
  C12T28SOI_LR_NOR2X3_P0 _170_ (
    .A(_109_),
    .B(_111_),
    .Z(_068_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _171_ (
    .A(i[27]),
    .B(_108_),
    .Z(_067_)
  );
  C12T28SOI_LR_AOI13X5_P0 _172_ (
    .A(i[25]),
    .B(i[24]),
    .C(_106_),
    .D(i[26]),
    .Z(_112_)
  );
  C12T28SOI_LR_NOR2X3_P0 _173_ (
    .A(_108_),
    .B(_112_),
    .Z(_066_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _174_ (
    .A(i[25]),
    .B(_107_),
    .Z(_065_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _175_ (
    .A(i[24]),
    .B(_106_),
    .Z(_064_)
  );
  C12T28SOI_LR_AOI13X5_P0 _176_ (
    .A(i[22]),
    .B(i[21]),
    .C(_104_),
    .D(i[23]),
    .Z(_113_)
  );
  C12T28SOI_LR_NOR2X3_P0 _177_ (
    .A(_106_),
    .B(_113_),
    .Z(_063_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _178_ (
    .A(i[22]),
    .B(_105_),
    .Z(_062_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _179_ (
    .A(i[21]),
    .B(_104_),
    .Z(_061_)
  );
  C12T28SOI_LR_AOI13X5_P0 _180_ (
    .A(i[19]),
    .B(i[18]),
    .C(_102_),
    .D(i[20]),
    .Z(_114_)
  );
  C12T28SOI_LR_NOR2X3_P0 _181_ (
    .A(_104_),
    .B(_114_),
    .Z(_060_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _182_ (
    .A(i[19]),
    .B(_103_),
    .Z(_059_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _183_ (
    .A(i[18]),
    .B(_102_),
    .Z(_058_)
  );
  C12T28SOI_LR_AOI13X5_P0 _184_ (
    .A(i[16]),
    .B(i[15]),
    .C(_100_),
    .D(i[17]),
    .Z(_115_)
  );
  C12T28SOI_LR_NOR2X3_P0 _185_ (
    .A(_102_),
    .B(_115_),
    .Z(_057_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _186_ (
    .A(i[16]),
    .B(_101_),
    .Z(_056_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _187_ (
    .A(i[15]),
    .B(_100_),
    .Z(_055_)
  );
  C12T28SOI_LR_AOI13X5_P0 _188_ (
    .A(i[13]),
    .B(i[12]),
    .C(_098_),
    .D(i[14]),
    .Z(_116_)
  );
  C12T28SOI_LR_NOR2X3_P0 _189_ (
    .A(_100_),
    .B(_116_),
    .Z(_054_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _190_ (
    .A(i[13]),
    .B(_099_),
    .Z(_053_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _191_ (
    .A(i[12]),
    .B(_098_),
    .Z(_052_)
  );
  C12T28SOI_LR_AOI13X5_P0 _192_ (
    .A(i[10]),
    .B(i[9]),
    .C(_096_),
    .D(i[11]),
    .Z(_117_)
  );
  C12T28SOI_LR_NOR2X3_P0 _193_ (
    .A(_098_),
    .B(_117_),
    .Z(_051_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _194_ (
    .A(i[10]),
    .B(_097_),
    .Z(_050_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _195_ (
    .A(i[9]),
    .B(_096_),
    .Z(_049_)
  );
  C12T28SOI_LR_AOI13X5_P0 _196_ (
    .A(i[7]),
    .B(i[6]),
    .C(_094_),
    .D(i[8]),
    .Z(_118_)
  );
  C12T28SOI_LR_NOR2X3_P0 _197_ (
    .A(_096_),
    .B(_118_),
    .Z(_048_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _198_ (
    .A(i[7]),
    .B(_095_),
    .Z(_047_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _199_ (
    .A(i[6]),
    .B(_094_),
    .Z(_046_)
  );
  C12T28SOI_LR_AOI13X5_P0 _200_ (
    .A(i[4]),
    .B(i[3]),
    .C(_092_),
    .D(i[5]),
    .Z(_119_)
  );
  C12T28SOI_LR_NOR2X3_P0 _201_ (
    .A(_094_),
    .B(_119_),
    .Z(_045_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _202_ (
    .A(i[4]),
    .B(_093_),
    .Z(_044_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _203_ (
    .A(i[3]),
    .B(_092_),
    .Z(_043_)
  );
  C12T28SOI_LRS_XOR2X6_P0 _204_ (
    .A(i[2]),
    .B(_091_),
    .Z(_042_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _205_ (
    .A(i[1]),
    .B(i[0]),
    .Z(_120_)
  );
  C12T28SOI_LR_NAND2X3_P0 _206_ (
    .A(i[1]),
    .B(_090_),
    .Z(_121_)
  );
  C12T28SOI_LR_OAI12X6_P0 _207_ (
    .A(_090_),
    .B(_120_),
    .C(_121_),
    .Z(_041_)
  );
  C12T28SOI_LRS_XNOR2X6_P0 _208_ (
    .A(i[0]),
    .B(_090_),
    .Z(_040_)
  );
  C12T28SOI_LR_NAND2X3_P0 _209_ (
    .A(out_data[5]),
    .B(_089_),
    .Z(_122_)
  );
  C12T28SOI_LR_OAI12X6_P0 _210_ (
    .A(_089_),
    .B(_120_),
    .C(_122_),
    .Z(_039_)
  );
  C12T28SOI_LR_NAND2X3_P0 _211_ (
    .A(out_data[4]),
    .B(_089_),
    .Z(_123_)
  );
  C12T28SOI_LR_OAI12X6_P0 _212_ (
    .A(i[0]),
    .B(_089_),
    .C(_123_),
    .Z(_038_)
  );
  C12T28SOI_LR_NAND2X3_P0 _213_ (
    .A(out_data[2]),
    .B(_089_),
    .Z(_124_)
  );
  C12T28SOI_LR_OAI12X6_P0 _214_ (
    .A(_075_),
    .B(_089_),
    .C(_124_),
    .Z(_037_)
  );
  C12T28SOI_LR_IVX4_P0 _215_ (
    .A(rst),
    .Z(_002_)
  );
  C12T28SOI_LR_IVX4_P0 _216_ (
    .A(rst),
    .Z(_003_)
  );
  C12T28SOI_LR_IVX4_P0 _217_ (
    .A(rst),
    .Z(_004_)
  );
  C12T28SOI_LR_IVX4_P0 _218_ (
    .A(rst),
    .Z(_005_)
  );
  C12T28SOI_LR_IVX4_P0 _219_ (
    .A(rst),
    .Z(_006_)
  );
  C12T28SOI_LR_IVX4_P0 _220_ (
    .A(rst),
    .Z(_007_)
  );
  C12T28SOI_LR_IVX4_P0 _221_ (
    .A(rst),
    .Z(_008_)
  );
  C12T28SOI_LR_IVX4_P0 _222_ (
    .A(rst),
    .Z(_009_)
  );
  C12T28SOI_LR_IVX4_P0 _223_ (
    .A(rst),
    .Z(_010_)
  );
  C12T28SOI_LR_IVX4_P0 _224_ (
    .A(rst),
    .Z(_011_)
  );
  C12T28SOI_LR_IVX4_P0 _225_ (
    .A(rst),
    .Z(_012_)
  );
  C12T28SOI_LR_IVX4_P0 _226_ (
    .A(rst),
    .Z(_013_)
  );
  C12T28SOI_LR_IVX4_P0 _227_ (
    .A(rst),
    .Z(_014_)
  );
  C12T28SOI_LR_IVX4_P0 _228_ (
    .A(rst),
    .Z(_015_)
  );
  C12T28SOI_LR_IVX4_P0 _229_ (
    .A(rst),
    .Z(_016_)
  );
  C12T28SOI_LR_IVX4_P0 _230_ (
    .A(rst),
    .Z(_017_)
  );
  C12T28SOI_LR_IVX4_P0 _231_ (
    .A(rst),
    .Z(_018_)
  );
  C12T28SOI_LR_IVX4_P0 _232_ (
    .A(rst),
    .Z(_019_)
  );
  C12T28SOI_LR_IVX4_P0 _233_ (
    .A(rst),
    .Z(_020_)
  );
  C12T28SOI_LR_IVX4_P0 _234_ (
    .A(rst),
    .Z(_021_)
  );
  C12T28SOI_LR_IVX4_P0 _235_ (
    .A(rst),
    .Z(_022_)
  );
  C12T28SOI_LR_IVX4_P0 _236_ (
    .A(rst),
    .Z(_023_)
  );
  C12T28SOI_LR_IVX4_P0 _237_ (
    .A(rst),
    .Z(_024_)
  );
  C12T28SOI_LR_IVX4_P0 _238_ (
    .A(rst),
    .Z(_025_)
  );
  C12T28SOI_LR_IVX4_P0 _239_ (
    .A(rst),
    .Z(_026_)
  );
  C12T28SOI_LR_IVX4_P0 _240_ (
    .A(rst),
    .Z(_027_)
  );
  C12T28SOI_LR_IVX4_P0 _241_ (
    .A(rst),
    .Z(_028_)
  );
  C12T28SOI_LR_IVX4_P0 _242_ (
    .A(rst),
    .Z(_029_)
  );
  C12T28SOI_LR_IVX4_P0 _243_ (
    .A(rst),
    .Z(_030_)
  );
  C12T28SOI_LR_IVX4_P0 _244_ (
    .A(rst),
    .Z(_031_)
  );
  C12T28SOI_LR_IVX4_P0 _245_ (
    .A(rst),
    .Z(_032_)
  );
  C12T28SOI_LR_IVX4_P0 _246_ (
    .A(rst),
    .Z(_033_)
  );
  C12T28SOI_LR_IVX4_P0 _247_ (
    .A(rst),
    .Z(_034_)
  );
  C12T28SOI_LR_IVX4_P0 _248_ (
    .A(rst),
    .Z(_035_)
  );
  C12T28SOI_LR_IVX4_P0 _249_ (
    .A(rst),
    .Z(_036_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _250_ (
    .CP(clk),
    .D(_037_),
    .Q(out_data[2]),
    .RN(_001_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _251_ (
    .CP(clk),
    .D(_038_),
    .Q(out_data[4]),
    .RN(_002_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _252_ (
    .CP(clk),
    .D(_039_),
    .Q(out_data[5]),
    .RN(_003_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _253_ (
    .CP(clk),
    .D(_000_),
    .Q(out_valid),
    .RN(_004_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _254_ (
    .CP(clk),
    .D(_040_),
    .Q(i[0]),
    .RN(_005_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _255_ (
    .CP(clk),
    .D(_041_),
    .Q(i[1]),
    .RN(_006_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _256_ (
    .CP(clk),
    .D(_042_),
    .Q(i[2]),
    .RN(_007_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _257_ (
    .CP(clk),
    .D(_043_),
    .Q(i[3]),
    .RN(_008_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _258_ (
    .CP(clk),
    .D(_044_),
    .Q(i[4]),
    .RN(_009_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _259_ (
    .CP(clk),
    .D(_045_),
    .Q(i[5]),
    .RN(_010_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _260_ (
    .CP(clk),
    .D(_046_),
    .Q(i[6]),
    .RN(_011_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _261_ (
    .CP(clk),
    .D(_047_),
    .Q(i[7]),
    .RN(_012_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _262_ (
    .CP(clk),
    .D(_048_),
    .Q(i[8]),
    .RN(_013_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _263_ (
    .CP(clk),
    .D(_049_),
    .Q(i[9]),
    .RN(_014_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _264_ (
    .CP(clk),
    .D(_050_),
    .Q(i[10]),
    .RN(_015_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _265_ (
    .CP(clk),
    .D(_051_),
    .Q(i[11]),
    .RN(_016_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _266_ (
    .CP(clk),
    .D(_052_),
    .Q(i[12]),
    .RN(_017_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _267_ (
    .CP(clk),
    .D(_053_),
    .Q(i[13]),
    .RN(_018_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _268_ (
    .CP(clk),
    .D(_054_),
    .Q(i[14]),
    .RN(_019_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _269_ (
    .CP(clk),
    .D(_055_),
    .Q(i[15]),
    .RN(_020_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _270_ (
    .CP(clk),
    .D(_056_),
    .Q(i[16]),
    .RN(_021_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _271_ (
    .CP(clk),
    .D(_057_),
    .Q(i[17]),
    .RN(_022_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _272_ (
    .CP(clk),
    .D(_058_),
    .Q(i[18]),
    .RN(_023_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _273_ (
    .CP(clk),
    .D(_059_),
    .Q(i[19]),
    .RN(_024_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _274_ (
    .CP(clk),
    .D(_060_),
    .Q(i[20]),
    .RN(_025_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _275_ (
    .CP(clk),
    .D(_061_),
    .Q(i[21]),
    .RN(_026_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _276_ (
    .CP(clk),
    .D(_062_),
    .Q(i[22]),
    .RN(_027_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _277_ (
    .CP(clk),
    .D(_063_),
    .Q(i[23]),
    .RN(_028_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _278_ (
    .CP(clk),
    .D(_064_),
    .Q(i[24]),
    .RN(_029_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _279_ (
    .CP(clk),
    .D(_065_),
    .Q(i[25]),
    .RN(_030_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _280_ (
    .CP(clk),
    .D(_066_),
    .Q(i[26]),
    .RN(_031_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _281_ (
    .CP(clk),
    .D(_067_),
    .Q(i[27]),
    .RN(_032_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _282_ (
    .CP(clk),
    .D(_068_),
    .Q(i[28]),
    .RN(_033_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _283_ (
    .CP(clk),
    .D(_069_),
    .Q(i[29]),
    .RN(_034_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _284_ (
    .CP(clk),
    .D(_070_),
    .Q(i[30]),
    .RN(_035_)
  );
  C12T28SOI_LR_DFPRQX17_P0 _285_ (
    .CP(clk),
    .D(_071_),
    .Q(i[31]),
    .RN(_036_)
  );
  assign out_data[1:0] = out_data[5:4];
  assign out_data[3] = 1'b0;
  assign out_data[7:6] = { 1'b0, out_data[2] };
endmodule

module tb_buffer_with_source_sink(rst, clk, src_valid, src_ready, buf_ready);
  wire [7:0] buf_out;
  output buf_ready;
  wire buf_ready;
  wire buf_valid;
  input clk;
  wire clk;
  input rst;
  wire rst;
  wire [7:0] src_data;
  output src_ready;
  wire src_ready;
  output src_valid;
  wire src_valid;
  buffer_ready_valid buffer (
    .clk(clk),
    .in_data(src_data),
    .in_ready(src_ready),
    .in_valid(src_valid),
    .out_data(buf_out),
    .out_ready(buf_ready),
    .out_valid(buf_valid),
    .rst(rst)
  );
  data_sink sink (
    .clk(clk),
    .in_data(buf_out),
    .in_ready(buf_ready),
    .in_valid(buf_valid),
    .rst(rst)
  );
  data_source source (
    .clk(clk),
    .out_data(src_data),
    .out_ready(src_ready),
    .out_valid(src_valid),
    .rst(rst)
  );
endmodule
