/* Generated by Yosys 0.43 (git sha1 ead4718e5, clang++ 15.0.0 -fPIC -Os) */

(* src = "in.v:1.1-21.10" *)
module tst(clk, in1, in2, in3, in4, in5, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "in.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "in.v:4.22-4.25" *)
  input in1;
  wire in1;
  (* src = "in.v:5.22-5.25" *)
  input in2;
  wire in2;
  (* src = "in.v:6.22-6.25" *)
  input in3;
  wire in3;
  (* src = "in.v:7.22-7.25" *)
  input in4;
  wire in4;
  (* src = "in.v:8.22-8.25" *)
  input in5;
  wire in5;
  (* src = "in.v:9.22-9.25" *)
  output out;
  wire out;
  DFFPOSX1 _05_ (
    .CLK(clk),
    .D(_00_),
    .Q(_01_)
  );
  DFFPOSX1 _06_ (
    .CLK(clk),
    .D(_02_),
    .Q(_03_)
  );
  AND2X1 _07_ (
    .A(_01_),
    .B(_03_),
    .Y(out)
  );
  AND2X1 _08_ (
    .A(in4),
    .B(in1),
    .Y(_00_)
  );
  NAND3X1 _09_ (
    .A(in5),
    .B(in3),
    .C(in2),
    .Y(_04_)
  );
  INVX1 _10_ (
    .A(_04_),
    .Y(_02_)
  );
endmodule
